global:
  namespaceOverride: "mongo"

architecture: standalone
useStatefulSet: true

auth:
  enabled: true
  rootUser: root
  existingSecret: mongodb-secret-dev
  
tls:
  enabled: false

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 500m
    memory: 2Gi

persistence:
  enabled: true
  storageClass: local-storage
  size: 10Gi

service:
  type: NodePort
  ports:
    mongodb: 27017
  nodePorts:
    mongodb: 31017
  externalTrafficPolicy: Cluster

nodeSelector:
  kubernetes.io/hostname: luckys-worker2
  kubernetes.io/arch: amd64

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: kwt-monitoring
    interval: 60s
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  collector:
    diagnosticdata: true
    replicasetstatus: true
    dbstats: true
    topmetrics: false
    indexstats: false
    collstats: false

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true

podSecurityContext:
  enabled: true
  fsGroup: 1001

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
