USER-SUPPLIED VALUES:
controller:
  containerEnv:
  - name: TZ
    value: Asia/Seoul
  image:
    pullPolicy: Always
    registry: docker.io
    repository: jenkins/jenkins
    tag: 2.479.2-lts-jdk17
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.100.0/24
    apiVersion: networking.k8s.io/v1
    enabled: true
    hostName: deploy.kwt.co.kr
    ingressClassName: nginx
    tls:
    - hosts:
      - deploy.kwt.co.kr
      secretName: deploy-jenkins-tls
  installPlugins:
  - credentials:1405.vb_cda_74a_f8974
  - kubernetes:4300.vd82c5692b_3a_e
  - workflow-api:1358.vfb_5780da_64cb_
  - workflow-aggregator:600.vb_57cdd26fdd7
  - git:5.5.2
  - git-client:6.1.0
  - configuration-as-code:1873.vea_5814ca_9c93
  - okhttp-api:4.11.0-181.v1de5b_83857df
  - display-url-api:2.209.v582ed814ff2f
  - mailer:488.v0c9639c1a_eb_3
  - scm-api:698.v8e3b_c788f0a_6
  persistence:
    enabled: true
    existingClaim: deploy-jenkins
    size: 8Gi
    storageClass: longhorn
  probes:
    startup:
      enabled: true
      failureThreshold: 12
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
fullnameOverride: deploy-jenkins
nameOverride: deploy-jenkins
