apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api
  namespace: kube-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.250
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 6443
      targetPort: 6443
  selector:
    component: kube-apiserver
    tier: control-plane
