apiVersion: v1
kind: ConfigMap
metadata:
  name: board-service-kafka-topics
  namespace: kafka
data:
  topics.json: |
    {
      "topics": [
        {
          "name": "dev.board-service.post.created",
          "partitions": 3,
          "replicationFactor": 2,
          "configs": {
            "retention.ms": "86400000",
            "cleanup.policy": "delete"
          }
        },
        {
          "name": "dev.board-service.post.updated",
          "partitions": 3,
          "replicationFactor": 2,
          "configs": {
            "retention.ms": "86400000",
            "cleanup.policy": "delete"
          }
        },
        {
          "name": "dev.board-service.post.deleted",
          "partitions": 3,
          "replicationFactor": 2,
          "configs": {
            "retention.ms": "86400000",
            "cleanup.policy": "delete"
          }
        },
        {
          "name": "dev.board-service.comment.created",
          "partitions": 3,
          "replicationFactor": 2,
          "configs": {
            "retention.ms": "86400000",
            "cleanup.policy": "delete"
          }
        },
        {
          "name": "dev.board-service.like.added",
          "partitions": 3,
          "replicationFactor": 2,
          "configs": {
            "retention.ms": "86400000",
            "cleanup.policy": "delete"
          }
        }
      ]
    }
